// Copyright 2026 Arachne Authors
// Licensed under the Apache License, Version 2.0.

// Generate the compact General_Category tables from UnicodeData.txt.
// Usage: node tools/generate_unicode.mjs /path/to/UnicodeData.txt > unicode_data.mbt

import fs from "node:fs";

const source = process.argv[2];
if (!source) {
  console.error("usage: node tools/generate_unicode.mjs UnicodeData.txt");
  process.exit(2);
}

const codes = new Map();
let pending = null;
for (const line of fs.readFileSync(source, "utf8").split(/\r?\n/)) {
  if (!line) continue;
  const fields = line.split(";");
  const code = Number.parseInt(fields[0], 16);
  const name = fields[1];
  const category = fields[2];
  if (name.endsWith(", First>")) {
    pending = { code, category };
  } else if (name.endsWith(", Last>")) {
    if (!pending || pending.category !== category) {
      throw new Error(`unpaired UnicodeData range at ${fields[0]}`);
    }
    for (let cp = pending.code; cp <= code; cp++) codes.set(cp, category);
    pending = null;
  } else {
    codes.set(code, category);
  }
}
if (pending) throw new Error("unterminated UnicodeData range");

const categories = new Set(["L", "M", "N", "P", "S", "Z", "C"]);
for (const category of codes.values()) categories.add(category);
const names = [...categories].sort();
const grouped = new Map(names.map((name) => [name, []]));
for (const [cp, category] of [...codes.entries()].sort((a, b) => a[0] - b[0])) {
  grouped.get(category).push(cp);
  grouped.get(category[0]).push(cp);
}
// UnicodeData omits most unassigned code points. General_Category=Cn is the
// complement of every assigned scalar value, excluding the surrogate block.
grouped.set("Cn", []);
for (let cp = 0; cp <= 0x10ffff; cp++) {
  if ((cp < 0xd800 || cp > 0xdfff) && !codes.has(cp)) {
    grouped.get("Cn").push(cp);
    grouped.get("C").push(cp);
  }
}
for (const values of grouped.values()) values.sort((a, b) => a - b);

function toRanges(values) {
  const ranges = [];
  for (const cp of values) {
    const last = ranges.at(-1);
    if (last && cp === last[1] + 1) last[1] = cp;
    else ranges.push([cp, cp]);
  }
  return ranges;
}

console.log("// Generated from Unicode 17.0 UnicodeData.txt; see tools/generate_unicode.mjs.");
console.log("// Do not edit this file by hand. Regenerate it for Unicode data updates.");
console.log("//|\npriv struct UnicodeRange { start : Int; end : Int }");
for (const name of names) {
  const ranges = toRanges(grouped.get(name));
  console.log(`\nlet unicode_${name} : Array[UnicodeRange] = [`);
  for (const [start, end] of ranges) {
    console.log(`  { start: ${start}, end: ${end}, },`);
  }
  console.log("]");
}
console.log("\nfn unicode_category_ranges(category : String) -> Array[UnicodeRange] {");
console.log("  match category {");
for (const name of names) console.log(`    ${JSON.stringify(name)} => unicode_${name}`);
console.log("    _ => []");
console.log("  }");
console.log("}");
